trigger:
- main
- dev
- feature/*
- bugfix/*
- issue/*

pr:
- main

variables:
  BASE_VERSION: 1.0
  NEW_VERSION: unset

stages:
- stage: CI
  jobs:
  - job: Build_NuGet_Package
    steps:
      - bash: |
          # Getting the latest version of the package form Nuget.Org
          PACKAGE_NAME="declaro.net"
          API_ENDPOINT="https://api.nuget.org/v3-flatcontainer/$PACKAGE_NAME/index.json"
          API_RESPONSE=$(curl -s "$API_ENDPOINT")
          ALL_VERSIONS=$(echo "$API_RESPONSE" | grep -o '"[0-9]\+\.[0-9]\+\.[0-9]\+"' | tr -d '"' | sort -V)
          LATEST_VERSION=$(echo "$ALL_VERSIONS" | tail -n 1)
          LATEST_MAJOR_VERSION=$(echo "$LATEST_VERSION" | cut -d'.' -f1)
          LATEST_MINOR_VERSION=$(echo "$LATEST_VERSION" | cut -d'.' -f2)
          LATEST_PATCH_VERSION=$(echo "$LATEST_VERSION" | cut -d'.' -f3)

          # Calculating the NEW_VERSION
          BASE_MAJOR_VERSION=$(echo "$BASE_VERSION" | cut -d'.' -f1)
          BASE_MINOR_VERSION=$(echo "$BASE_VERSION" | cut -d'.' -f2)
          if [ "$BASE_MAJOR_VERSION" -gt "$LATEST_MAJOR_VERSION" ] || [ "$BASE_MINOR_VERSION" -gt "$LATEST_MINOR_VERSION" ]; then
          NEW_VERSION="$BASE_MAJOR_VERSION.$BASE_MINOR_VERSION.0"
          else
          NEW_PATCH_VERSION=$((LATEST_PATCH_VERSION + 1))
          NEW_VERSION="$BASE_MAJOR_VERSION.$BASE_MINOR_VERSION.$NEW_PATCH_VERSION"
          fi

          echo "##vso[task.setvariable variable=NEW_VERSION;]$NEW_VERSION"
        displayName: Set version of new package
        condition: eq(variables['Build.SourceBranchName'], 'main')
      - task: UseDotNet@2
        displayName: 'Use .NET Core SDK version 7.x'
        inputs:
          packageType: sdk
          version: 7.x
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: 'src/Declaro.Net.Test/Declaro.Net.Tests.csproj'
      - task: DotNetCoreCLI@2
        displayName: Build NuGet package
        inputs:
          command: 'pack'
          packagesToPack: 'src/Declaro.Net/Declaro.Net.csproj'
          configuration: 'Release'
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'NEW_VERSION'
      - task: PublishBuildArtifacts@1
        displayName: Push .nupgk file to Artifacts
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'nupkg'
          publishLocation: 'Container'
        condition: eq(variables['Build.SourceBranchName'], 'main')
- stage: CD
  dependsOn: CI
  condition: and(ne(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.SourceBranchName'], 'main'))
  jobs:
    # Using deplyoment job here to control environment and pre-approval for nuget.org public feed deployment
    - deployment: Deploy_To_NugetOrg_Public_Feed
      environment:
        name: Public NugetOrg feed
      strategy:
       runOnce:
         deploy:
           steps:
             - task: DownloadBuildArtifacts@1
               displayName: Pull .nupgk file from Artifacts
               inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'nupkg'
                downloadPath: '$(System.ArtifactsDirectory)'
             - task: NuGetCommand@2
               displayName: Publish .nupkg to public nuget.org feed
               inputs:
                command: 'push'
                packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'nuget.org'